/**
 * Build + zip script for Zalo Mini App deployment.
 *
 * Usage:     npm run zip:zma
 *
 * Steps:
 *   1. Vite build with mode "zma" -> output to www/
 *   2. Remove files not needed for ZMA (e.g. 404.html for GitHub Pages)
 *   3. Replace app-config.json with correct ZMA v2 format
 *   4. Zip www/ -> attendance-app-zma.zip
 */

import { execSync } from "child_process";
import {
  createWriteStream,
  existsSync,
  mkdirSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from "fs";
import { join, resolve } from "path";
import { readFile, stat } from "fs/promises";
import { ZipArchive } from "archiver";

const ROOT = resolve(import.meta.dirname, "..");
const SCRIPTS = join(ROOT, "scripts");
const DIST = join(ROOT, "www");
const OUT_DIR = join(SCRIPTS, "zma-package");
const OUT_ZIP = join(OUT_DIR, "attendance-app-zma.zip");

async function main() {
  // 1. Build
  console.log("[1/2] Building for Zalo Mini App...");
  execSync("npx vite build --mode zma", { cwd: ROOT, stdio: "inherit" });

  if (!existsSync(DIST)) {
    console.error("ERROR: www/ folder not found after build");
    process.exit(1);
  }

  // 2. Remove files not needed for ZMA
  const removeFiles = ["404.html", "favicon.svg", "icons.svg"];
  for (const file of removeFiles) {
    const filePath = join(DIST, file);
    if (existsSync(filePath)) unlinkSync(filePath);
  }

  // 3. Replace app-config.json with correct ZMA v2 format
  //    NOTE: Only include ZMA v2 required fields (app + pages),
  //    NOT the full zma-config.json which has extra fields (mpId, name, etc.)
  //    that would cause "File app-config.json is invalid" error on upload.
  console.log("   Writing ZMA v2 app-config.json...");
  const zmaConfigPath = join(SCRIPTS, "zma-config.json");
  const zmaConfig = JSON.parse(readFileSync(zmaConfigPath, "utf-8"));

  const distConfigPath = join(DIST, "app-config.json");

  // Build ZMA v2 app-config.json: merge zma-config.json fields
  // with any list* fields already generated by zmp-vite-plugin (if exist)
  let existingConfig = {};
  try {
    existingConfig = JSON.parse(readFileSync(distConfigPath, "utf-8"));
  } catch {
    // zmp-vite-plugin may not have generated one yet
  }

  const appConfigV2 = {
    app: zmaConfig.app,
    pages: zmaConfig.pages,
    permissions: zmaConfig.permissions || ["scope.userInfo"],
    listCSS: existingConfig.listCSS || [],
    listSyncJS: existingConfig.listSyncJS || [],
    listAsyncJS: existingConfig.listAsyncJS || [],
  };

  writeFileSync(distConfigPath, JSON.stringify(appConfigV2, null, 2));

  // 4. Ensure output directory exists
  if (!existsSync(OUT_DIR)) {
    mkdirSync(OUT_DIR, { recursive: true });
  }

  // 5. Remove old zip
  if (existsSync(OUT_ZIP)) unlinkSync(OUT_ZIP);

  // 6. Create zip
  console.log("[2/2] Creating zip archive...");
  await new Promise((resolve, reject) => {
    const output = createWriteStream(OUT_ZIP);
    const archive = new ZipArchive({ zlib: { level: 9 } });

    output.on("close", resolve);
    output.on("error", reject);
    archive.on("error", reject);

    archive.pipe(output);
    archive.directory(DIST, false);
    archive.finalize();
  });

  // 7. Show result
  const pkg2 = JSON.parse(await readFile(join(ROOT, "package.json"), "utf-8"));
  const stats = await stat(OUT_ZIP);
  const sizeMB = (stats.size / 1024 / 1024).toFixed(2);

  console.log("\nDone!");
  console.log("   File:  " + OUT_ZIP);
  console.log("   Size:  " + sizeMB + " MB");
  console.log("   Ver:   " + pkg2.version);
  console.log("\nUpload this zip to https://mini.zalo.me/");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
